/** Live reference catalogs. No credentials are included in exported fixtures. */
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { z } = require('zod');
const FIXTURES = process.env.PORTLOG_TEST_CATALOG_DIR || path.join(__dirname, 'catalog-fixtures');
if (process.env.PORTLOG_TEST_CATALOG_DIR) {
  const target = new URL(process.env.DATABASE_URL || 'postgresql://invalid/invalid');
  if (!['localhost', '127.0.0.1'].includes(target.hostname) || !target.pathname.endsWith('_test'))
    throw new Error('Test catalogs require an isolated loopback database ending in _test');
}
const TABLES = ['activities', 'cargoes'];
const timestamp = z
  .string()
  .refine(
    (v) => /^\d{4}-\d\d-\d\d[T ]\d\d:\d\d:\d\d(?:\.\d{1,6})?[+-]\d\d(?::?\d\d)?$/.test(v),
    'Expected a PostgreSQL timestamp with timezone',
  );
const base = {
  id: z.string().min(1),
  name: z.string().min(1),
  comments: z.string().nullable(),
  createdAt: timestamp,
  updatedAt: timestamp,
};
const schemas = {
  activities: z.object(base).strict(),
  cargoes: z.object({ ...base, bblUnit: z.string(), category: z.enum(['SN', 'OT']) }).strict(),
};
function canonical(rows) {
  return JSON.stringify(
    [...rows]
      .sort((a, b) => a.id.localeCompare(b.id))
      .map((row) =>
        Object.fromEntries(
          Object.keys(row)
            .sort()
            .map((key) => [key, row[key]]),
        ),
      ),
  );
}
function checksum(rows) {
  return crypto.createHash('sha256').update(canonical(rows)).digest('hex');
}
function sourceIdentity(url) {
  const u = new URL(url);
  return {
    host: u.hostname,
    port: u.port || '5432',
    database: decodeURIComponent(u.pathname.slice(1)),
    schema: u.searchParams.get('schema') || 'public',
  };
}
function validateRows(table, rows) {
  const parsed = z.array(schemas[table]).parse(rows);
  if (new Set(parsed.map((r) => r.id)).size !== parsed.length)
    throw new Error(`Duplicate ${table} IDs in capture`);
  return parsed;
}
function readFixtures(directory = FIXTURES) {
  const manifest = JSON.parse(fs.readFileSync(path.join(directory, 'manifest.json'), 'utf8'));
  if (manifest.version !== 1 || !manifest.source || !manifest.capturedAt)
    throw new Error('Invalid catalog manifest');
  const catalogs = {};
  for (const table of TABLES) {
    const rows = validateRows(
      table,
      JSON.parse(fs.readFileSync(path.join(directory, `${table}.json`), 'utf8')),
    );
    if (
      manifest.tables?.[table]?.count !== rows.length ||
      manifest.tables[table].sha256 !== checksum(rows)
    )
      throw new Error(`Catalog verification failed: ${table}`);
    catalogs[table] = rows;
  }
  return { manifest, catalogs };
}
async function readLive(prisma) {
  // JSON generated by PostgreSQL preserves microseconds, unlike JS Date.
  return prisma.$transaction(
    async (tx) => {
      await tx.$executeRawUnsafe("SET LOCAL TIME ZONE 'UTC'");
      const catalogs = {};
      for (const table of TABLES) {
        const rows = await tx.$queryRawUnsafe(
          `SELECT row_to_json(t)::text AS row FROM "${table}" t ORDER BY id`,
        );
        catalogs[table] = validateRows(
          table,
          rows.map((r) => JSON.parse(r.row)),
        );
      }
      const migrations = await tx.$queryRawUnsafe(
        'SELECT migration_name FROM _prisma_migrations WHERE finished_at IS NOT NULL AND rolled_back_at IS NULL ORDER BY migration_name',
      );
      return { catalogs, migrations: migrations.map((m) => m.migration_name) };
    },
    { isolationLevel: 'RepeatableRead' },
  );
}
async function exportCatalogs(prisma, url, directory = FIXTURES) {
  const { catalogs, migrations } = await readLive(prisma);
  if (TABLES.some((table) => catalogs[table].length === 0))
    throw new Error('Refusing to replace a live capture with an empty catalog');
  const manifest = {
    version: 1,
    source: sourceIdentity(url),
    capturedAt: new Date().toISOString(),
    migrations,
    tables: {},
  };
  fs.mkdirSync(directory, { recursive: true });
  for (const table of TABLES) {
    manifest.tables[table] = { count: catalogs[table].length, sha256: checksum(catalogs[table]) };
    fs.writeFileSync(
      path.join(directory, `${table}.json`),
      JSON.stringify(catalogs[table], null, 2) + '\n',
    );
  }
  fs.writeFileSync(path.join(directory, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
  readFixtures(directory);
  return manifest;
}
async function verifySource(prisma, url, directory = FIXTURES) {
  const { manifest, catalogs } = readFixtures(directory);
  if (JSON.stringify(sourceIdentity(url)) !== JSON.stringify(manifest.source))
    throw new Error('Reset target differs from the captured live catalog source');
  const current = await readLive(prisma);
  for (const table of TABLES)
    if (checksum(current.catalogs[table]) !== checksum(catalogs[table]))
      throw new Error(`Live ${table} changed; freeze writes and capture again before reset`);
  return manifest;
}
async function restoreCatalogs(prisma, directory = FIXTURES) {
  const { catalogs } = readFixtures(directory);
  await prisma.$transaction(async (tx) => {
    for (const table of TABLES)
      for (const row of catalogs[table]) {
        await tx.$executeRawUnsafe(
          `INSERT INTO "${table}" SELECT * FROM json_populate_record(NULL::"${table}", $1::json) ON CONFLICT (id) DO NOTHING`,
          JSON.stringify(row),
        );
      }
  });
}
async function verifyRestored(prisma, directory = FIXTURES) {
  const { catalogs } = readFixtures(directory);
  const current = await readLive(prisma);
  for (const table of TABLES)
    if (checksum(current.catalogs[table]) !== checksum(catalogs[table]))
      throw new Error(`Restored ${table} differs from live capture`);
}
module.exports = {
  TABLES,
  canonical,
  checksum,
  sourceIdentity,
  validateRows,
  readFixtures,
  exportCatalogs,
  verifySource,
  restoreCatalogs,
  verifyRestored,
};
if (require.main === module) {
  require('dotenv').config({ path: path.join(__dirname, '../.env'), quiet: true });
  const { PrismaClient } = require('@prisma/client');
  const prisma = new PrismaClient();
  (async () => {
    const command = process.argv[2];
    if (command === 'export') {
      const manifest = await exportCatalogs(prisma, process.env.DATABASE_URL);
      console.log(JSON.stringify({ capturedAt: manifest.capturedAt, tables: manifest.tables }));
    } else if (command === 'verify') {
      const { manifest } = readFixtures();
      console.log(JSON.stringify(manifest.tables));
    } else if (command === 'check-source') {
      await verifySource(prisma, process.env.DATABASE_URL);
      console.log('Live catalog capture verified.');
    } else if (command === 'verify-restored') {
      await verifyRestored(prisma);
      console.log('Restored catalogs match.');
    } else throw new Error('Use export, verify, check-source, or verify-restored');
  })()
    .catch((error) => {
      console.error(error.message);
      process.exitCode = 1;
    })
    .finally(() => prisma.$disconnect());
}
