/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteImport } from './routes/login';
import { Route as ProtectedRouteImport } from './routes/_protected';
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index';
import { Route as ProtectedMasterDataRouteImport } from './routes/_protected/master-data';
import { Route as ProtectedMasterDataShippersRouteImport } from './routes/_protected/master-data/shippers';
import { Route as ProtectedMasterDataOperatorsRouteImport } from './routes/_protected/master-data/operators';
import { Route as ProtectedMasterDataFlagsRouteImport } from './routes/_protected/master-data/flags';
import { Route as ProtectedMasterDataCharterersRouteImport } from './routes/_protected/master-data/charterers';
import { Route as ProtectedMasterDataCargoesRouteImport } from './routes/_protected/master-data/cargoes';
import { Route as ProtectedMasterDataAgentsRouteImport } from './routes/_protected/master-data/agents';
import { Route as ProtectedMasterDataActivitiesRouteImport } from './routes/_protected/master-data/activities';
import { Route as ProtectedMasterData_demoRouteImport } from './routes/_protected/master-data/__demo';

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedMasterDataRoute = ProtectedMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedMasterDataShippersRoute = ProtectedMasterDataShippersRouteImport.update({
  id: '/shippers',
  path: '/shippers',
  getParentRoute: () => ProtectedMasterDataRoute,
} as any);
const ProtectedMasterDataOperatorsRoute = ProtectedMasterDataOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => ProtectedMasterDataRoute,
} as any);
const ProtectedMasterDataFlagsRoute = ProtectedMasterDataFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => ProtectedMasterDataRoute,
} as any);
const ProtectedMasterDataCharterersRoute = ProtectedMasterDataCharterersRouteImport.update({
  id: '/charterers',
  path: '/charterers',
  getParentRoute: () => ProtectedMasterDataRoute,
} as any);
const ProtectedMasterDataCargoesRoute = ProtectedMasterDataCargoesRouteImport.update({
  id: '/cargoes',
  path: '/cargoes',
  getParentRoute: () => ProtectedMasterDataRoute,
} as any);
const ProtectedMasterDataAgentsRoute = ProtectedMasterDataAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ProtectedMasterDataRoute,
} as any);
const ProtectedMasterDataActivitiesRoute = ProtectedMasterDataActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => ProtectedMasterDataRoute,
} as any);
const ProtectedMasterData_demoRoute = ProtectedMasterData_demoRouteImport.update({
  id: '/__demo',
  getParentRoute: () => ProtectedMasterDataRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute;
  '/login': typeof LoginRoute;
  '/master-data': typeof ProtectedMasterData_demoRoute;
  '/master-data/activities': typeof ProtectedMasterDataActivitiesRoute;
  '/master-data/agents': typeof ProtectedMasterDataAgentsRoute;
  '/master-data/cargoes': typeof ProtectedMasterDataCargoesRoute;
  '/master-data/charterers': typeof ProtectedMasterDataCharterersRoute;
  '/master-data/flags': typeof ProtectedMasterDataFlagsRoute;
  '/master-data/operators': typeof ProtectedMasterDataOperatorsRoute;
  '/master-data/shippers': typeof ProtectedMasterDataShippersRoute;
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute;
  '/master-data': typeof ProtectedMasterData_demoRoute;
  '/': typeof ProtectedIndexRoute;
  '/master-data/activities': typeof ProtectedMasterDataActivitiesRoute;
  '/master-data/agents': typeof ProtectedMasterDataAgentsRoute;
  '/master-data/cargoes': typeof ProtectedMasterDataCargoesRoute;
  '/master-data/charterers': typeof ProtectedMasterDataCharterersRoute;
  '/master-data/flags': typeof ProtectedMasterDataFlagsRoute;
  '/master-data/operators': typeof ProtectedMasterDataOperatorsRoute;
  '/master-data/shippers': typeof ProtectedMasterDataShippersRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_protected': typeof ProtectedRouteWithChildren;
  '/login': typeof LoginRoute;
  '/_protected/master-data': typeof ProtectedMasterDataRouteWithChildren;
  '/_protected/': typeof ProtectedIndexRoute;
  '/_protected/master-data/__demo': typeof ProtectedMasterData_demoRoute;
  '/_protected/master-data/activities': typeof ProtectedMasterDataActivitiesRoute;
  '/_protected/master-data/agents': typeof ProtectedMasterDataAgentsRoute;
  '/_protected/master-data/cargoes': typeof ProtectedMasterDataCargoesRoute;
  '/_protected/master-data/charterers': typeof ProtectedMasterDataCharterersRoute;
  '/_protected/master-data/flags': typeof ProtectedMasterDataFlagsRoute;
  '/_protected/master-data/operators': typeof ProtectedMasterDataOperatorsRoute;
  '/_protected/master-data/shippers': typeof ProtectedMasterDataShippersRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/master-data'
    | '/master-data/activities'
    | '/master-data/agents'
    | '/master-data/cargoes'
    | '/master-data/charterers'
    | '/master-data/flags'
    | '/master-data/operators'
    | '/master-data/shippers';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/login'
    | '/master-data'
    | '/'
    | '/master-data/activities'
    | '/master-data/agents'
    | '/master-data/cargoes'
    | '/master-data/charterers'
    | '/master-data/flags'
    | '/master-data/operators'
    | '/master-data/shippers';
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/master-data'
    | '/_protected/'
    | '/_protected/master-data/__demo'
    | '/_protected/master-data/activities'
    | '/_protected/master-data/agents'
    | '/_protected/master-data/cargoes'
    | '/_protected/master-data/charterers'
    | '/_protected/master-data/flags'
    | '/_protected/master-data/operators'
    | '/_protected/master-data/shippers';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected': {
      id: '/_protected';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected/': {
      id: '/_protected/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof ProtectedIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/master-data': {
      id: '/_protected/master-data';
      path: '/master-data';
      fullPath: '/master-data';
      preLoaderRoute: typeof ProtectedMasterDataRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/master-data/shippers': {
      id: '/_protected/master-data/shippers';
      path: '/shippers';
      fullPath: '/master-data/shippers';
      preLoaderRoute: typeof ProtectedMasterDataShippersRouteImport;
      parentRoute: typeof ProtectedMasterDataRoute;
    };
    '/_protected/master-data/operators': {
      id: '/_protected/master-data/operators';
      path: '/operators';
      fullPath: '/master-data/operators';
      preLoaderRoute: typeof ProtectedMasterDataOperatorsRouteImport;
      parentRoute: typeof ProtectedMasterDataRoute;
    };
    '/_protected/master-data/flags': {
      id: '/_protected/master-data/flags';
      path: '/flags';
      fullPath: '/master-data/flags';
      preLoaderRoute: typeof ProtectedMasterDataFlagsRouteImport;
      parentRoute: typeof ProtectedMasterDataRoute;
    };
    '/_protected/master-data/charterers': {
      id: '/_protected/master-data/charterers';
      path: '/charterers';
      fullPath: '/master-data/charterers';
      preLoaderRoute: typeof ProtectedMasterDataCharterersRouteImport;
      parentRoute: typeof ProtectedMasterDataRoute;
    };
    '/_protected/master-data/cargoes': {
      id: '/_protected/master-data/cargoes';
      path: '/cargoes';
      fullPath: '/master-data/cargoes';
      preLoaderRoute: typeof ProtectedMasterDataCargoesRouteImport;
      parentRoute: typeof ProtectedMasterDataRoute;
    };
    '/_protected/master-data/agents': {
      id: '/_protected/master-data/agents';
      path: '/agents';
      fullPath: '/master-data/agents';
      preLoaderRoute: typeof ProtectedMasterDataAgentsRouteImport;
      parentRoute: typeof ProtectedMasterDataRoute;
    };
    '/_protected/master-data/activities': {
      id: '/_protected/master-data/activities';
      path: '/activities';
      fullPath: '/master-data/activities';
      preLoaderRoute: typeof ProtectedMasterDataActivitiesRouteImport;
      parentRoute: typeof ProtectedMasterDataRoute;
    };
    '/_protected/master-data/__demo': {
      id: '/_protected/master-data/__demo';
      path: '';
      fullPath: '/master-data';
      preLoaderRoute: typeof ProtectedMasterData_demoRouteImport;
      parentRoute: typeof ProtectedMasterDataRoute;
    };
  }
}

interface ProtectedMasterDataRouteChildren {
  ProtectedMasterData_demoRoute: typeof ProtectedMasterData_demoRoute;
  ProtectedMasterDataActivitiesRoute: typeof ProtectedMasterDataActivitiesRoute;
  ProtectedMasterDataAgentsRoute: typeof ProtectedMasterDataAgentsRoute;
  ProtectedMasterDataCargoesRoute: typeof ProtectedMasterDataCargoesRoute;
  ProtectedMasterDataCharterersRoute: typeof ProtectedMasterDataCharterersRoute;
  ProtectedMasterDataFlagsRoute: typeof ProtectedMasterDataFlagsRoute;
  ProtectedMasterDataOperatorsRoute: typeof ProtectedMasterDataOperatorsRoute;
  ProtectedMasterDataShippersRoute: typeof ProtectedMasterDataShippersRoute;
}

const ProtectedMasterDataRouteChildren: ProtectedMasterDataRouteChildren = {
  ProtectedMasterData_demoRoute: ProtectedMasterData_demoRoute,
  ProtectedMasterDataActivitiesRoute: ProtectedMasterDataActivitiesRoute,
  ProtectedMasterDataAgentsRoute: ProtectedMasterDataAgentsRoute,
  ProtectedMasterDataCargoesRoute: ProtectedMasterDataCargoesRoute,
  ProtectedMasterDataCharterersRoute: ProtectedMasterDataCharterersRoute,
  ProtectedMasterDataFlagsRoute: ProtectedMasterDataFlagsRoute,
  ProtectedMasterDataOperatorsRoute: ProtectedMasterDataOperatorsRoute,
  ProtectedMasterDataShippersRoute: ProtectedMasterDataShippersRoute,
};

const ProtectedMasterDataRouteWithChildren = ProtectedMasterDataRoute._addFileChildren(
  ProtectedMasterDataRouteChildren,
);

interface ProtectedRouteChildren {
  ProtectedMasterDataRoute: typeof ProtectedMasterDataRouteWithChildren;
  ProtectedIndexRoute: typeof ProtectedIndexRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedMasterDataRoute: ProtectedMasterDataRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(ProtectedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
